-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE I.REST_ID = R.REST_ID AND ADDRESS LIKE "서울%"
GROUP BY I.REST_ID
HAVING AVG(R.REVIEW_SCORE) IS NOT NULL AND I.FAVORITES IS NOT NULL AND I.REST_ID IS NOT NULL
ORDER BY SCORE DESC, I.FAVORITES DESC;