SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    GENDER, 
    COUNT(DISTINCT S.USER_ID) AS USERS -- 주의!
FROM 
    ONLINE_SALE S JOIN USER_INFO U 
    ON S.USER_ID=U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3